// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/21/2026, 1:32:44 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/hotel-booking-system/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/hotel-booking-system/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/hotel-booking-system/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/hotel-booking-system/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/hotel-booking-system/frontend/plugins/**/*.{js,ts,mjs}","D:/hotel-booking-system/frontend/composables/**/*.{js,ts,mjs}","D:/hotel-booking-system/frontend/utils/**/*.{js,ts,mjs}","D:/hotel-booking-system/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/hotel-booking-system/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/hotel-booking-system/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/hotel-booking-system/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;