name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronized

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR Title and Commits
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Pull Request Check
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # PR Title ကို Conventional Commit format ကိုက်ညီမှု ရှိ/မရှိ စစ်ဆေးခြင်း
          types: |
            feat
            fix
            refactor
            chore
            docs
            test
            style
            ci
          requireScope: false
          # PR Title အပြင်၊ အထဲက commit message တွေ အားလုံးကိုပါ စစ်ချင်ရင် true ပေးပါ
          validateSingleCommit: true